version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: m3ak_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: m3ak_user
      POSTGRES_PASSWORD: m3ak_password
      POSTGRES_DB: m3ak_db
    volumes:
      - m3ak_db:/var/lib/postgresql/data

volumes:
  m3ak_db: